// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    partial class RepositoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Jane Doe",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = 3,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Sam Smith",
                            PhoneNumber = "555-666-7777"
                        },
                        new
                        {
                            Id = 4,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "Alice Johnson",
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 5,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Bob Brown",
                            PhoneNumber = "222-333-4444"
                        },
                        new
                        {
                            Id = 6,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Charlie White",
                            PhoneNumber = "333-444-5555"
                        },
                        new
                        {
                            Id = 7,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "David Black",
                            PhoneNumber = "444-555-6666"
                        },
                        new
                        {
                            Id = 8,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Eve Green",
                            PhoneNumber = "555-666-7777"
                        },
                        new
                        {
                            Id = 9,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Frank Red",
                            PhoneNumber = "666-777-8888"
                        },
                        new
                        {
                            Id = 10,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "Grace Blue",
                            PhoneNumber = "777-888-9999"
                        },
                        new
                        {
                            Id = 11,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Henry Silver",
                            PhoneNumber = "888-999-0000"
                        },
                        new
                        {
                            Id = 12,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Isla Gold",
                            PhoneNumber = "999-000-1111"
                        },
                        new
                        {
                            Id = 13,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "Jack Brown",
                            PhoneNumber = "000-111-2222"
                        },
                        new
                        {
                            Id = 14,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Karen White",
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 15,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Leo Black",
                            PhoneNumber = "222-333-4444"
                        },
                        new
                        {
                            Id = 16,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "Mia Red",
                            PhoneNumber = "333-444-5555"
                        },
                        new
                        {
                            Id = 17,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Nina Green",
                            PhoneNumber = "444-555-6666"
                        },
                        new
                        {
                            Id = 18,
                            ContactType = "Work",
                            GroupId = 3,
                            Name = "Oscar Blue",
                            PhoneNumber = "555-666-7777"
                        },
                        new
                        {
                            Id = 19,
                            ContactType = "Mobile",
                            GroupId = 1,
                            Name = "Peter Silver",
                            PhoneNumber = "666-777-8888"
                        },
                        new
                        {
                            Id = 20,
                            ContactType = "Home",
                            GroupId = 2,
                            Name = "Quinn Gold",
                            PhoneNumber = "777-888-9999"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ContactGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "Family"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "Friends"
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "Work"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.HasOne("Domain.Entities.ContactGroup", "Group")
                        .WithMany("Contacts")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Domain.Entities.ContactGroup", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
